---
version: '2.1'

services:
    dev1.group_1:
        hostname: dev1.group_1
        image: dbarroso/stupid_ssh_container
        ports:
            - "65020:22"

    dev2.group_1:
        hostname: dev2.group_1
        image: dbarroso/stupid_ssh_container
        ports:
            - "65021:22"

    dev3.group_2:
        hostname: dev3.group_2
        image: dbarroso/stupid_ssh_container
        ports:
            - "65022:22"

    dev4.group_2:
        hostname: dev4.group_2
        image: dbarroso/stupid_ssh_container
        ports:
            - "65023:22"

    dev5.no_group:
        hostname: dev5.no_group
        image: dbarroso/stupid_ssh_container
        ports:
            - "65024:22"

    netconf1.no_group:
        hostname: netconf1.no_group
        image: sysrepo/sysrepo-netopeer2:latest
        ports:
            - "65025:830"

    httpbin:
        hostname: httpbin
        image: bungoume/httpbin-container
        ports:
            - "65080:80"
